apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customers-api
  template:
    metadata:
      labels:
        tier: backend
        app: customers-api
    spec:
      containers:
      - name: customers-api
        image: gcr.io/inretail-tpo-challenge/customers-api:latest
        imagePullPolicy: Always
        volumeMounts:
          - name: config-volume
            mountPath: /app/application.properties
            subPath: application.properties
        env:
          - name: JAVA_OPTS
            value: -Dmicronaut.config.files=file:/app/application.properties
        envFrom:
          - secretRef: 
              name: customers-api-secret
      volumes:
        - name: config-volume
          configMap:
            name: customers-api