apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: customers-api
  annotations:
    kubernetes.io/ingress.global-static-ip-name: inretail-tpo-challenge-ip
    cert-manager.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/tls-acme: "true"
  labels:
    app: customers-api
spec:
  backend:
    serviceName: customers-api
    servicePort: 8080
  rules:
  - host: api.mvillarreal.com
    http:
      paths:
      - backend:
          serviceName: customers-api
          servicePort: 8080
        path: /
  tls:
    - hosts:
      - api.mvillarreal.com
      secretName: customers-api-secret