docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - ./mvwn clean package
    - docker build --pull -t "$CI_REGISTRY_IMAGE":"$CI_COMMIT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE"
  variables:
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""

deploy-dev:
  stage: deploy
  image: bitnami/kubectl
  script:
    - kubectl get deployment customers-api || kubectl apply -f ./deploy --image="$CI_REGISTRY_IMAGE":"$CI_COMMIT_SHA" -n dev
    - kubectl set image deployment/customers-api customers-api="$CI_REGISTRY_IMAGE":"$CI_COMMIT_SHA" -n dev
  only:
    - dev

deploy-qa:
  stage: deploy
  image: bitnami/kubectl
  script:
    - kubectl get deployment customers-api || kubectl create deployment customers-api --image="$CI_REGISTRY_IMAGE":"$CI_COMMIT_SHA"
    - kubectl set image deployment/customers-api customers-api="$CI_REGISTRY_IMAGE":"$CI_COMMIT_SHA"
  only:
    - qa

deploy-prod:
  stage: deploy
  image: bitnami/kubectl
  script:
    - kubectl get deployment customers-api || kubectl create deployment customers-api --image="$CI_REGISTRY_IMAGE":"$CI_COMMIT_SHA"
    - kubectl set image deployment/customers-api customers-api="$CI_REGISTRY_IMAGE":"$CI_COMMIT_SHA"
  only:
    - master