name: customers-api:CI/CD
on:
  push:
    branches:
    - master
env:
  PROJECT_ID: mvillarreal-tpo-challenge
  CLUSTER_ID: inretail-tpo-challenge-cluster
  ZONE: us-central1-a
  REGISTRY: mvillarreal-tpo-challenge/customers-api
  DEPLOY: customers-api
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build application Jar
      id: build
      working-directory: ./customers-api
      run: ./mvnw clean package
    - name: build & publish image
      uses: mr-smithers-excellent/docker-build-push@v1.0
      with:
       image: mvillarreal-tpo-challenge/customers-api
       tag: ${{ github.sha }}
       registry: gcr.io
       username: _json_key
       password: ${{ secrets.DOCKER_PASSWORD }}
    - name: setup gcloud
      id: gcloudsetup
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCLOUD_KEY }}
    - name: deploy to google kubernetes engine
      id: deploy
      run: |
        gcloud container clusters get-credentials $CLUSTER_ID --zone $ZONE --project $PROJECT_ID 
        kubectl get deploy $DEPLOY  -n apps || kubectl apply -f ./customers-api/deploy -n apps
        kubectl set image deploy/$DEPLOY  $DEPLOY=gcr.io/$REGISTRY:${{ github.sha }}  -n apps