name: customers-api:CI/CD
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build application Jar
      working-directory: ./customers-api
      run: ./mvnw clean package
    - name: Login to gcloud registry
      id: gcloud
      uses: elgohr/gcloud-login-action@master
      with:
        account_key: ${{ secrets.GCLOUD_KEY }}
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_KEY }}
    - name: Create and push image
      if: success()
      uses: manusa/actions-publish-docker@master
      working-directory: ./customers-api
      with:
        name: inretail-tpo-challenge/customers-api
        tag: ${{ github.sha }}
        username: ${{ steps.gcloud.outputs.username }}
        password: ${{ steps.gcloud.outputs.password }}
        registry: gcr.io