name: customers-api:CI/CD
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build application Jar
      id: build
      working-directory: ./customers-api
      run: ./mvnw clean package
    - name: build & publish image
      uses: mr-smithers-excellent/docker-build-push@v1.0
      with:
       image: inretail-tpo-challenge/customers-api
       tag: ${{ github.sha }}
       registry: gcr.io
       username: _json_key
       password: ${{ secrets.DOCKER_PASSWORD }}
    - name: deploy to google kubernetes engine
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCLOUD_KEY }}
      run: |
        kubectl get deploy customers-api -n apps || kubectl apply -f ./customers-api/deploy -n apps
        kubectl set image deploy/gcr.io/inretail-tpo-challenge/customers-api:${{ github.sha }} -n apps