name: customers-api:CI/CD
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build application Jar
      working-directory: ./customers-api
      run: ./mvnw clean package
    - name: Login to gcloud registry
      id: gcloud
      uses: elgohr/gcloud-login-action@master
      with:
        account_key: ${{ secrets.GCLOUD_KEY }}
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_KEY }}
    - name: Build & publish image
      uses: mr-smithers-excellent/docker-build-push@v1.0
      with:
       image: inretail-tpo-challenge/customers-api
       registry: gcr.io
       dockerfile: ./customers-api/Dockerfile
       username: _json_key
       password: ${{ secrets.DOCKER_PASSWORD }} 